apiVersion: v1
kind: Pod
metadata:
  name: pr25
  namespace: portainer
spec:
  containers:
  - name: pr25
    image: portainerci/portainer-ee:pr25-linux-amd64
  imagePullSecrets:
  - name: wconquestdockercreds
  ports:
    - containerPort: 9000
